apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
      #clusterIP: None
  type: NodePort
  ports: 
    - name: postgres
      port: 5432
      nodePort: 30432
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
