apiVersion: apps/v1
kind: Deployment
metadata:
  name:  counter-app
  labels:
    app:  counter-app
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  counter-app
    spec:
      containers:
      - name:  counter-app
        image:  counter:1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
        # args: ["-c", "sleep 10000"]
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: counter-app-config
          - secretRef:
              name: counter-app-secret
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
      nodeSelector:
        tier: db
